INSERT INTO person (name) VALUES ('person-1')
INSERT INTO person (name) VALUES ('person-2')
INSERT INTO person (name) VALUES ('person-3')
INSERT INTO person (name) VALUES ('person-4')
INSERT INTO person (name) VALUES ('person-5')
INSERT INTO person (name) VALUES ('person-6')
